name: PR-Django CI (SQLite)

on:
  push:
    branches: ["**"]   
  pull_request:
    branches: ['main']
  
jobs:
  build:
    runs-on: ubuntu-latest
   # if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}

    env:
      DJANGO_SETTINGS_MODULE: config.settings.settings_local
      SECRET_KEY: test-secret-key   # âœ” use a dummy key, safe for forks (FAKE KEY)
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (ASK Charly why requirements not all deps)
        run: |
          python -m pip install --upgrade pip         
         
          cat requirements-dev.txt
          pip install -r requirements-dev.txt 
          pip install -r requirements.txt
          
      
      - name: Ghis is trying to print Debug working directory
        run: pwd && ls -R              

      - name: Run migrations to ensure build run correctly
        run: |
          python manage.py migrate
  
  nextjob:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Just for testing
        run: | 
             ls
  

  lastjob:
    runs-on: ubuntu-latest
    needs: nextjob
    steps:
      - name: Just for testing
        run: | 
             ls